language: python
python:
  - '3.8'
sudo: required
install:
  - pip install -e .[dev]
script:
  - pytest --cov=opentargets_validator --cov-report term tests/ --fulltrace
deploy:
  provider: pypi
  skip_existing: true
  user: "${PYPI_USERNAME}"
  password: "${PYPI_PASSWORD}"
  on:
    tags: true
  distributions: "sdist bdist_wheel"

notifications:
  email:
    recipients:
    - data@opentargets.org
    on_success: never
    on_failure: always
after_success:
  - codecov
