version: 2.1
orbs:
  codecov: codecov/codecov@3.2.2
jobs:
  build_test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            python3 -m pip install --upgrade build pip setuptools
            python3 -m build
            pytest
  pypi_publish:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run:
          command: |
            python3 setup.py verify  # Check that the version being released matches between git, CircleCI and package
            python3 -m twine upload dist/* -u"${PYPI_USERNAME}" -p"${PYPI_PASSWORD}"
workflows:
  build_test_publish:
    jobs:
      - build_test
      - codecov/upload:
          requires:
            - build_test
      - pypi_publish:
          requires:
            - build_test
          filters:
            branches:
              only:
                - main
